inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Severity: warning

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
   - config/**/*
   - spec/**/*
Style/Documentation:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case
