  
name: RspecTests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        # The postgres container requires the postgres user to be setup with a password in order to start it due to security
        # reasons
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-
    - name: Setup the Rails application
      env:
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        cp config/database.github.yml config/database.yml
        bundle exec rails db:create
        bundle exec rails db:migrate
        yarn --frozen-lockfile
    - name: Run Rspec
      run: bundle exec rspec
    - name: Simplecov Report
      uses: aki77/simplecov-report-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        failedThreshold: 0
